os: linux
sudo: false
language: python

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py

    - python: '3.6'
      env: TOXENV=py

    - os: osx
      language: generic
      env: TOXENV=py PYBREW=python2

    - os: osx
      language: generic
      env: TOXENV=py PYBREW=python3

before_install:
    # Perform the manual steps on osx to install python3 and activate venv
    # (see http://blog.fizyk.net.pl/blog/running-python-tests-on-traviss-osx-workers.html)
    # (see also https://github.com/pallets/flask/blob/master/.travis.yml)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew upgrade python;
      brew link 
      if [[ "$PYBREW" == "python3" ]]; then
        python3 -m pip install -q virtualenv;
        python3 -m virtualenv -p python3 ~/py-env;
      else
        brew link --force
        python2 -m pip install -q virtualenv;
        python2 -m virtualenv -p python2 ~/py-env;
      fi
      source ~/py-env/bin/activate;
    fi
  - python --version
  - virtualenv --version
  - easy_install --version
  - pip --version

install:
  - pip install tox

script:
  - python -m tox -v

after_success:
  - pip install codecov
  - codecov

cache:
  - pip

branches:
  only:
    - master
    - /^.*-feature$/
    - /^.*-maintenance$/

notifications:
  email: false