language: python
sudo: false
branches:
  only:
    - codecov
before_install:
  - echo === Before Install.
  - virtualenv --version
  - easy_install --version
install:
  - echo === Install.
  - pip install tox
  - tox --version
before_script:
  - echo === Before Script.
  - python --version
script:
  - echo === Run Test Script 1.
after_script:
  - echo === After Script.
after_failure:
  - echo === After Failure.
after_success:
  - echo === After Success.
jobs:
  include:
    - script:
        - echo === Run Test Script 2. TXPY=$TOXPYTHON
        - python --version
    - python: '3.4'
      env: TOXPYTHON=py34
      script:
        - echo === Run Test Script 3. TXPY=$TOXPYTHON
        - python --version
    - stage: cov
      script:
        - echo === Coverage Stage!
        - python --version
