language: python
sudo: false
matrix:
  include:
    - python: 2.6
    - python: 3.5
before_install:
  - echo === Before Install.
  - virtualenv --version
  - easy_install --version
install:
  - echo === Install.
  - pip install tox
  - tox --version
before_script:
  - echo === Before Script.
  - python --version
script:
  - echo === Run Script.
  - python -c "print('Hello world!')"
after_script:
  - echo === After Script.
after_failure:
  - echo === After Failure.
after_success:
  - echo === After Success.
jobs:
  include:
    - stage: cov
      script:
        - python -c "print('-----------\nHello world!')"
        - python --version
        - python -c "print('-----------')"
