language: python
sudo: false
branches:
  only:
    - codecov
before_install:
  - echo === Before Install.
  - virtualenv --version
  - easy_install --version
install:
  - echo === Install.
  - pip install tox
  - tox --version
before_script:
  - echo === Before Script.
  - python --version
script:
  - echo === Run Test Script 1. TOXPYTHON=$TOXPYTHON
  - python --version
after_script:
  - echo === After Script.
after_failure:
  - echo === After Failure.
after_success:
  - echo === After Success.
jobs:
  include:
    - python: '2.7'
      env: TOXPYTHON=py27
    - python: '3.4'
      env: TOXPYTHON=py34
