language: python
sudo: false
matrix:
  include:
    - python: 2.6
      env: TOXPYTHON=py26
    - python: 3.5
      env: TOXPYTHON=py35
before_install:
  - echo === Before Install.
  - virtualenv --version
  - easy_install --version
install:
  - echo === Install.
  - pip install tox
  - tox --version
before_script:
  - echo === Before Script.
  - python --version
script:
  - echo === Run Test Script 1.
after_script:
  - echo === After Script.
after_failure:
  - echo === After Failure.
after_success:
  - echo === After Success.
jobs:
  include:
    - script:
        - echo === Run Test Script 2. TXPY=$TOXPYTHON
    - stage: cov
      script:
        - echo === Coverage Stage!
        - python --version
