language: python
sudo: false
python:
  - "2.7"
  - "3.6"
before_install:
  - echo === Before Install.
  - virtualenv --version
  - easy_install --version
install:
  - echo === Install.
  - pip install tox
  - tox --version
before_script:
  - echo === Before Script.
  - python --version
script:
  - echo === Run Script.
  - python -c "print('Hello world!')"
after_script:
  - echo === After Script.
after_failure:
  - echo === After Failure.
after_success:
  - echo === After Success.
