build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
  - ps: echo $env:PYTHON
  - cmd: dir %PYTHON%
  - python --version
  - python -c "import struct;print(8 * struct.calcsize(\'P\'))"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - python -m pip install tox
  - python -m pip install wheel
  - python -m virtualenv --version
  - python -m easy_install --version
  - python -m pip --version
  - python -m tox --version

test_script:
  - python -m tox

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - python -m pip install codecov
    - python -m codecov
