environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

init:
  - ps: ls C:\Python*
  - ps: echo $env:PYTHON
  - ps: echo $env:TOXENV
  - cmd: dir %PYTHON%
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - "python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - python -m pip install tox
  - python -m pip install wheel
  - python -m virtualenv --version
  - python -m easy_install --version
  - python -m pip --version
  - python -m tox --version

build: off

test_script:
  - python -m tox

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - python -m pip install codecov
    - python -m codecov

cache:
  - '%LOCALAPPDATA%\pip\Cache'

branches:
  only:
    - master
    - /^.*-feature$/
    - /^.*-maintenance$/
