build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
  - "%PYTHON%/python.exe --version"
  - "%PYTHON%/python.exe -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "%PYTHON%\\python.exe -m pip install tox"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m virtualenv --version"
  - "%PYTHON%\\python.exe -m easy_install --version"
  - "%PYTHON%\\python.exe -m pip --version"
  - "%PYTHON%\\python.exe -m tox --version"

test_script:
  - "%PYTHON%\\python.exe -m tox"

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - "%PYTHON%\\python.exe -m pip install codecov"
    - set OS=WINDOWS
    - "%PYTHON%\\Scripts\\codecov"
